[package]
name = "bevy_time"
version = "0.1.0"
authors = ["SecretPocketCat <jiridexterhanc@gmail.com>"]
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "07ed1d053e7946a116ce3eef273fc93dd246f49d", default-features = false }
